/**
 * MyRollmate – Localisation (lang.js)
 *
 * Provides the full i18n dictionary for all UI strings and exposes a
 * translate helper used by every other module.
 *
 * Loaded before: audio.js, 3d-engine.js, roll-logic.js, ui-handler.js, main.js
 */

window.RollmateLang = (() => {
  // --- I18N DICTIONARY ---
  const langDict = {
    en: {
      btn_skills: "Skill Checks",
      btn_init: "Combat Preparation",
      start_combat: "Start Combat",
      btn_random: "Cards of Destiny",
      btn_start_roulette: "Choose your card",
      who_title: "WHO IS PARTICIPATING?",
      drop_actor: "DRAG & DROP ACTOR OR SELECT",
      proceed: "PROCEED TO SETUP",
      btn_wheel: "CARDS OF DESTINY!",
      roll_it: "ROLL IT!",
      setup_title: "SETUP",
      tab_skills: "SKILLS",
      tab_saves: "SAVES",
      tab_abilities: "ABILITY CHECKS",
      tab_flat: "FLAT / UNMODIFIED",
      sel_global: "-- Select Global --",
      adj_diff: "Adjust Difficulty",
      pass_fail: "Pass / Fail",
      hidden_gm: "Hidden",
      finish: "FINISH & RESOLVE",
      spin: "SHUFFLE",
      close: "CLOSE",
      init_rolls: "Initiative Rolls",
      mixed_rolls: "Mixed Rolls",
      waiting: "Waiting...",
      result_crit_fail: "Crit. Failure",
      result_fail: "Failure",
      result_succ: "Success",
      result_crit_succ: "Crit. Success",
      init_text: "INITIATIVE",
      level_dc: "LEVEL BASED DC",
      dc_adj: "DC ADJUSTMENT",
      flat_straight: "Straight d20",
      flat_death: "Death Save",
      flat_persistent: "Persistent Damage",
      flat_concealed: "Concealed",
      flat_hidden: "Hidden",
      flat_recovery: "Recovery Check",
      resol_title: "🎬 Rollmate Results",
      secret_title: "🕵️ GM Secret Rolls: Rollmate",
      started_title: "🎬 Rollmate Started",
      click_wheel: "Click to watch the cards!",
      click_dice: "Click portrait to roll!",
      open_win: "OPEN WINDOW",
      gather_party: "Gather Party!",
      gather_all: "Gather All",
      prep_combat: "Gather combatants",
      art_colors: "Colours",
      art_hover: "Hover Color",
      art_border: "Window Frame",
      art_dice_head: "Dice Design",
      art_dice_style_stone: "Stone",
      art_dice_style_coal: "Coal",
      art_dice_style_wood: "Wood",
      art_fonts: "Fonts",
      art_sounds: "Sounds and Ambiente",
      art_anim: "Animations and Effects",
      art_design: "My Design",
      art_dev: "In Development",
      art_bg_bright: "Wallpaper Brightness",
      art_bg_trans: "Wallpaper Transparency",
      art_bg_title: "Wallpaper",
      art_card_design: "Card Design",
      art_choose_card: "Choose Card",
      art_particle_color: "Particle",
      art_test_roll: "Test Roll",
      map_warning_title: "Map required!",
      map_warning_desc:
        "Only participants on the current map can be added.<br>If you want to add other actors, please place them on the map .",
      mode_immersive: "Immersive Board",
      mode_classic: "Classic Board",
      limit_title: "Too many participants!",
      limit_desc:
        "Too many participants selected for the Immersive Board (Max 10). Do you want to reduce the participants or switch to Classic Mode?",
      limit_red: "Reduce",
      limit_class: "Use Classic Mode",
      settings_perf: "Performance",
      settings_vol: "Volume",
      exit: "EMERGENCY EXIT",
      acr: "Acrobatics",
      ani: "Animal Handling",
      arc: "Arcana",
      ath: "Athletics",
      dec: "Deception",
      his: "History",
      ins: "Insight",
      itm: "Intimidation",
      inv: "Investigation",
      med: "Medicine",
      nat: "Nature",
      prc: "Perception",
      prf: "Performance",
      per: "Persuasion",
      rel: "Religion",
      slt: "Sleight of Hand",
      ste: "Stealth",
      sur: "Survival",
      str: "Strength",
      dex: "Dexterity",
      con: "Constitution",
      int: "Intelligence",
      wis: "Wisdom",
      cha: "Charisma",
      abl_str: "Strength",
      abl_dex: "Dexterity",
      abl_con: "Constitution",
      abl_int: "Intelligence",
      abl_wis: "Wisdom",
      abl_cha: "Charisma",
      acrobatics: "Acrobatics",
      arcana: "Arcana",
      athletics: "Athletics",
      crafting: "Crafting",
      deception: "Deception",
      diplomacy: "Diplomacy",
      intimidation: "Intimidation",
      medicine: "Medicine",
      nature: "Nature",
      occultism: "Occultism",
      perception: "Perception",
      performance: "Performance",
      religion: "Religion",
      society: "Society",
      stealth: "Stealth",
      survival: "Survival",
      thievery: "Thievery",
      fortitude: "Fortitude",
      reflex: "Reflex",
      will: "Will",
    },
    de: {
      btn_skills: "Fertigkeitswürfe",
      btn_init: "Kampfvorbereitung",
      start_combat: "Kampf starten",
      btn_random: "Schicksalskarten",
      btn_start_roulette: "Wähle deine Karte",
      who_title: "WER NIMMT TEIL?",
      drop_actor: "AKTEUR ZIEHEN ODER AUSWÄHLEN",
      proceed: "WEITER ZUM SETUP",
      btn_wheel: "SCHICKSALSKARTEN!",
      roll_it: "WÜRFELN!",
      setup_title: "SETUP",
      tab_skills: "FERTIGKEITEN",
      tab_saves: "RETTUNGSWÜRFE",
      tab_abilities: "ATTRIBUTSWÜRFE",
      tab_flat: "FLACHE WÜRFE",
      sel_global: "-- Global wählen --",
      adj_diff: "Schwierigkeit anpassen",
      pass_fail: "Pass / Fail",
      hidden_gm: "Verdeckt",
      finish: "BEENDEN & AUFLÖSEN",
      spin: "MISCHEN",
      close: "SCHLIESSEN",
      init_rolls: "Initiativwürfe",
      mixed_rolls: "Gemischte Würfe",
      waiting: "Wartet...",
      result_crit_fail: "Krit. Fehlschlag",
      result_fail: "Fehlschlag",
      result_succ: "Erfolg",
      result_crit_succ: "Krit. Erfolg",
      init_text: "INITIATIVE",
      level_dc: "STUFENBASIERTER SG",
      dc_adj: "SG ANPASSUNG",
      flat_straight: "Einfacher Wurf (W20)",
      flat_death: "Todesrettungswurf",
      flat_persistent: "Dauerhafter Schaden",
      flat_concealed: "Verborgen",
      flat_hidden: "Versteckt",
      flat_recovery: "Erholungs-Wurf",
      resol_title: "🎬 Rollmate Results",
      secret_title: "🕵️ Geheime SL Würfe: Rollmate",
      started_title: "🎬 Rollmate Gestartet",
      click_wheel: "Klicke, um die Karten zu sehen!",
      click_dice: "Klicke auf das Portrait zum Würfeln!",
      open_win: "FENSTER ÖFFNEN",
      gather_party: "Gruppe Sammeln!",
      gather_all: "Alle Sammeln",
      prep_combat: "Kämpfer versammeln",
      art_colors: "Farben",
      art_hover: "Hover Farbe",
      art_border: "Fensterrahmen",
      art_dice_head: "Würfel Design",
      art_dice_style_stone: "Stein",
      art_dice_style_coal: "Kohle",
      art_dice_style_wood: "Holz",
      art_fonts: "Schriftarten",
      art_sounds: "Sounds und Ambiente",
      art_anim: "Animationen und Effekte",
      art_design: "Mein Design",
      art_dev: "In Entwicklung",
      art_bg_bright: "Wallpaper Leuchtkraft",
      art_bg_trans: "Wallpaper Transparenz",
      art_bg_title: "Wallpaper",
      art_card_design: "Kartendesign",
      art_choose_card: "Karte Wählen",
      art_particle_color: "Partikel",
      art_test_roll: "Testwurf",
      map_warning_title: "Map benötigt!",
      map_warning_desc:
        "Nur Teilnehmer auf der aktuellen Map können hinzugefügt werden.<br>Willst du andere Actor hinzufügen, so platziere sie bitte auf der Map.",
      mode_immersive: "Immersive Board",
      mode_classic: "Classic Board",
      limit_title: "Zuviele Teilnehmer!",
      limit_desc:
        "Zuviele Teilnehmer für das Immersive Board (Maximal 10). Teilnehmer reduzieren oder in den Classic Mode wechseln?",
      limit_red: "Reduzieren",
      limit_class: "Classic Mode nutzen",
      settings_perf: "Leistung",
      settings_vol: "Lautstärke",
      exit: "NOTAUSSTIEG",
      acr: "Akrobatik",
      ani: "Mit Tieren umgehen",
      arc: "Arkanes Wissen",
      ath: "Athletik",
      dec: "Täuschung",
      his: "Geschichte",
      ins: "Motiv erkennen",
      itm: "Einschüchtern",
      inv: "Nachforschungen",
      med: "Heilkunde",
      nat: "Natur",
      prc: "Wahrnehmung",
      prf: "Auftreten",
      per: "Überzeugen",
      rel: "Religion",
      slt: "Fingerfertigkeit",
      ste: "Heimlichkeit",
      sur: "Überleben",
      str: "Stärke",
      dex: "Geschicklichkeit",
      con: "Konstitution",
      int: "Intelligenz",
      wis: "Weisheit",
      cha: "Charisma",
      abl_str: "Stärke",
      abl_dex: "Geschicklichkeit",
      abl_con: "Konstitution",
      abl_int: "Intelligenz",
      abl_wis: "Weisheit",
      abl_cha: "Charisma",
      acrobatics: "Akrobatik",
      arcana: "Arkane Kunst",
      athletics: "Athletik",
      crafting: "Handwerkskunst",
      deception: "Täuschung",
      diplomacy: "Diplomatie",
      intimidation: "Einschüchtern",
      medicine: "Heilkunde",
      nature: "Natur",
      occultism: "Okkultismus",
      perception: "Wahrnehmung",
      performance: "Darbietung",
      religion: "Religion",
      society: "Gesellschaft",
      stealth: "Heimlichkeit",
      survival: "Überlebenskunst",
      thievery: "Diebeskunst",
      fortitude: "Zähigkeit",
      reflex: "Reflex",
      will: "Wille",
    },
    es: {
      btn_skills: "Pruebas de Habilidad",
      btn_init: "Preparación de Combate",
      start_combat: "Iniciar Combate",
      btn_random: "Cartas del Destino",
      btn_start_roulette: "Elige tu carta",
      who_title: "¿QUIÉN PARTICIPA?",
      drop_actor: "ARRASTRAR ACTOR O SELECCIONAR",
      proceed: "IR A CONFIGURACIÓN",
      btn_wheel: "¡CARTAS DEL DESTINO!",
      roll_it: "¡TIRAR!",
      setup_title: "CONFIGURACIÓN",
      tab_skills: "HABILIDADES",
      tab_saves: "SALVACIONES",
      tab_abilities: "CARACTERÍSTICAS",
      tab_flat: "TIRADAS PLANAS",
      sel_global: "-- Seleccionar Global --",
      adj_diff: "Ajustar Dificultad",
      pass_fail: "Éxito / Fallo",
      hidden_gm: "Oculto",
      finish: "TERMINAR Y RESOLVER",
      spin: "BARAJAR",
      close: "CERRAR",
      init_rolls: "Tiradas de Iniciativa",
      mixed_rolls: "Tiradas Mixtas",
      waiting: "Esperando...",
      result_crit_fail: "Fallo Crítico",
      result_fail: "Fallo",
      result_succ: "Éxito",
      result_crit_succ: "Éxito Crítico",
      init_text: "INICIATIVA",
      level_dc: "CD POR NIVEL",
      dc_adj: "AJUSTE DE CD",
      flat_straight: "D20 Normal",
      flat_death: "Salvación de Muerte",
      flat_persistent: "Daño Persistente",
      flat_concealed: "Oculto",
      flat_hidden: "Escondido",
      flat_recovery: "Tirada de Recuperación",
      resol_title: "🎬 Resultados Rollmate",
      secret_title: "🕵️ Tiradas Secretas: Rollmate",
      started_title: "🎬 Rollmate Iniciado",
      click_wheel: "¡Haz clic para ver las cartas!",
      click_dice: "¡Haz clic en el retrato para tirar!",
      open_win: "ABRIR VENTANA",
      gather_party: "¡Reunir Grupo!",
      gather_all: "Reunir Todos",
      prep_combat: "Reunir combatientes",
      art_colors: "Colores",
      art_hover: "Color Hover",
      art_border: "Marco de Ventana",
      art_dice_head: "Diseño de Dados",
      art_dice_style_stone: "Piedra",
      art_dice_style_coal: "Carbón",
      art_dice_style_wood: "Madera",
      art_fonts: "Fuentes",
      art_sounds: "Sonidos y Ambiente",
      art_anim: "Animaciones y Efectos",
      art_design: "Mi Diseño",
      art_dev: "En Desarrollo",
      art_bg_bright: "Brillo del Fondo",
      art_bg_trans: "Transparencia del Fondo",
      art_bg_title: "Fondo",
      art_card_design: "Diseño de Cartas",
      art_choose_card: "Elegir Carta",
      art_particle_color: "Partícula",
      art_test_roll: "Tirada de Prueba",
      map_warning_title: "¡Se requiere mapa!",
      map_warning_desc:
        "Solo se pueden añadir participantes del mapa actual.<br>Colócalos primero en el mapa.",
      mode_immersive: "Tablero Inmersivo",
      mode_classic: "Tablero Clásico",
      limit_title: "¡Demasiados participantes!",
      limit_desc:
        "Demasiados participantes (Máx 10). ¿Quieres reducir los participantes o usar el Modo Clásico?",
      limit_red: "Reducir",
      limit_class: "Modo Clásico",
      settings_perf: "Rendimiento",
      settings_vol: "Volumen",
      exit: "SALIDA DE EMERGENCIA",
      acr: "Acrobacias",
      ani: "Trato con animales",
      arc: "Conocimiento Arcano",
      ath: "Atletismo",
      dec: "Engaño",
      his: "Historia",
      ins: "Perspicacia",
      itm: "Intimidación",
      inv: "Investigación",
      med: "Medicina",
      nat: "Naturaleza",
      prc: "Percepción",
      prf: "Interpretación",
      per: "Persuasión",
      rel: "Religión",
      slt: "Juego de Manos",
      ste: "Sigilo",
      sur: "Supervivencia",
      str: "Fuerza",
      dex: "Destreza",
      con: "Constitución",
      int: "Inteligencia",
      wis: "Sabiduría",
      cha: "Carisma",
      abl_str: "Fuerza",
      abl_dex: "Destreza",
      abl_con: "Constitución",
      abl_int: "Inteligencia",
      abl_wis: "Sabiduría",
      abl_cha: "Carisma",
      acrobatics: "Acrobacias",
      arcana: "Arcano",
      athletics: "Atletismo",
      crafting: "Artesanía",
      deception: "Engaño",
      diplomacy: "Diplomacia",
      intimidation: "Intimidación",
      medicine: "Medicina",
      nature: "Naturaleza",
      occultism: "Ocultismo",
      perception: "Percepción",
      performance: "Interpretación",
      religion: "Religión",
      society: "Sociedad",
      stealth: "Sigilo",
      survival: "Supervivencia",
      thievery: "Latrocinio",
      fortitude: "Fortaleza",
      reflex: "Reflejos",
      will: "Voluntad",
    },
    fr: {
      btn_skills: "Jets de Compétence",
      btn_init: "Préparation au Combat",
      start_combat: "Lancer le Combat",
      btn_random: "Cartes du Destino",
      btn_start_roulette: "Choisissez votre carte",
      who_title: "QUI PARTICIPE ?",
      drop_actor: "GLISSER-DÉPOSER UN ACTEUR OU SÉLECTIONNER",
      proceed: "PASSER À LA CONFIGURATION",
      btn_wheel: "CARTES DU DESTIN !",
      roll_it: "LANCER !",
      setup_title: "CONFIGURATION",
      tab_skills: "COMPÉTENCES",
      tab_saves: "SAUVEGARDES",
      tab_abilities: "CARACTÉRISTIQUES",
      tab_flat: "JETS SIMPLES",
      sel_global: "-- Sélection Globale --",
      adj_diff: "Ajuster la Difficulté",
      pass_fail: "Succès / Échec",
      hidden_gm: "Caché",
      finish: "TERMINER ET RÉSOUDRE",
      spin: "MÉLANGER",
      close: "FERMER",
      init_rolls: "Jets d'Initiative",
      mixed_rolls: "Jets Mixtes",
      waiting: "En attente...",
      result_crit_fail: "Échec Critique",
      result_fail: "Échec",
      result_succ: "Succès",
      result_crit_succ: "Succès Critique",
      init_text: "INITIATIVE",
      level_dc: "DD PAR NIVEAU",
      dc_adj: "AJUSTEMENT DD",
      flat_straight: "D20 Simple",
      flat_death: "Jet de Sauvegarde contre la Mort",
      flat_persistent: "Dégâts Persistants",
      flat_concealed: "Dissimulé",
      flat_hidden: "Caché",
      flat_recovery: "Jet de Récupération",
      resol_title: "🎬 Résultats Rollmate",
      secret_title: "🕵️ Jets Secrets : Rollmate",
      started_title: "🎬 Rollmate Démarré",
      click_wheel: "Cliquez pour voir les cartes !",
      click_dice: "Cliquez sur le portrait pour lancer !",
      open_win: "OUVRIR LA FENÊTRE",
      gather_party: "Rassembler le Groupe !",
      gather_all: "Rassembler Tous",
      prep_combat: "Rassembler les combattants",
      art_colors: "Couleurs",
      art_hover: "Couleur de Survol",
      art_border: "Cadre de la Fenêtre",
      art_dice_head: "Design des Dés",
      art_dice_style_stone: "Pierre",
      art_dice_style_coal: "Charbon",
      art_dice_style_wood: "Bois",
      art_fonts: "Polices",
      art_sounds: "Sons et Ambiance",
      art_anim: "Animations et Effets",
      art_design: "Mon Design",
      art_dev: "En Développement",
      art_bg_bright: "Luminosité du Fond",
      art_bg_trans: "Transparence du Fond",
      art_bg_title: "Fond",
      art_card_design: "Design des Cartes",
      art_choose_card: "Choisir la Carte",
      art_particle_color: "Particule",
      art_test_roll: "Jet de Test",
      map_warning_title: "Carte requise !",
      map_warning_desc:
        "Seuls les participants sur la carte actuelle peuvent être ajoutés.",
      mode_immersive: "Plateau Immersif",
      mode_classic: "Plateau Classique",
      limit_title: "Trop de participants !",
      limit_desc:
        "Trop de participants (Max 10). Voulez-vous les réduire ou passer au Mode Classique ?",
      limit_red: "Réduire",
      limit_class: "Utiliser Mode Classique",
      settings_perf: "Performance",
      settings_vol: "Volume",
      exit: "SORTIE DE SECOURS",
      acr: "Acrobaties",
      ani: "Dressage",
      arc: "Arcanes",
      ath: "Athlétisme",
      dec: "Tromperie",
      his: "Histoire",
      ins: "Perspicacité",
      itm: "Intimidation",
      inv: "Investigation",
      med: "Médecine",
      nat: "Nature",
      prc: "Perception",
      prf: "Représentation",
      per: "Persuasion",
      rel: "Religion",
      slt: "Escamotage",
      ste: "Discrétion",
      sur: "Survie",
      str: "Force",
      dex: "Dextérité",
      con: "Constitution",
      int: "Intelligence",
      wis: "Sagesse",
      cha: "Charisme",
      abl_str: "Force",
      abl_dex: "Dextérité",
      abl_con: "Constitution",
      abl_int: "Intelligence",
      abl_wis: "Sagesse",
      abl_cha: "Charisme",
      acrobatics: "Acrobaties",
      arcana: "Arcanes",
      athletics: "Athlétisme",
      crafting: "Artisanat",
      deception: "Duperie",
      diplomacy: "Diplomatie",
      intimidation: "Intimidation",
      medicine: "Médecine",
      nature: "Nature",
      occultism: "Occultisme",
      perception: "Perception",
      performance: "Représentation",
      religion: "Religion",
      society: "Société",
      stealth: "Discrétion",
      survival: "Survie",
      thievery: "Vol",
      fortitude: "Vigueur",
      reflex: "Réflexes",
      will: "Volonté",
    },
    pt: {
      btn_skills: "Testes de Perícia",
      btn_init: "Preparação de Combate",
      start_combat: "Iniciar Combate",
      btn_random: "Cartas do Destino",
      btn_start_roulette: "Escolha sua carta",
      who_title: "QUEM PARTICIPA?",
      drop_actor: "ARRASTAR ATOR OU SELECIONAR",
      proceed: "PROSSEGUIR PARA CONFIGURAÇÃO",
      btn_wheel: "CARTAS DO DESTINO!",
      roll_it: "ROLAR!",
      setup_title: "CONFIGURAZIONE",
      tab_skills: "PERÍCIAS",
      tab_saves: "SALVAMENTOS",
      tab_abilities: "HABILIDADES",
      tab_flat: "ROLAGENS PLANAS",
      sel_global: "-- Seleção Global --",
      adj_diff: "Ajustar Dificuldade",
      pass_fail: "Sucesso / Falha",
      hidden_gm: "Oculto",
      finish: "CONCLUIR E RESOLVER",
      spin: "EMBARALHAR",
      close: "FECHAR",
      init_rolls: "Rolagens de Iniciativa",
      mixed_rolls: "Rolagens Mistas",
      waiting: "Aguardando...",
      result_crit_fail: "Falha Crítica",
      result_fail: "Falha",
      result_succ: "Sucesso",
      result_crit_succ: "Sucesso Crítico",
      init_text: "INICIATIVA",
      level_dc: "CD POR NÍVEL",
      dc_adj: "AJUSTE DE CD",
      flat_straight: "D20 Normal",
      flat_death: "Salvamento de Morte",
      flat_persistent: "Dano Persistente",
      flat_concealed: "Oculto",
      flat_hidden: "Escondido",
      flat_recovery: "Teste de Recuperação",
      resol_title: "🎬 Resultados Rollmate",
      secret_title: "🕵️ Rolagens Secretas: Rollmate",
      started_title: "🎬 Rollmate Iniciado",
      click_wheel: "Clique para ver as cartas!",
      click_dice: "Clique no retrato para rolar!",
      open_win: "ABRIR JANELA",
      gather_party: "Reunir Grupo!",
      gather_all: "Reunir Todos",
      prep_combat: "Reunir combatientes",
      art_colors: "Cores",
      art_hover: "Cor Hover",
      art_border: "Borda da Janela",
      art_dice_head: "Design dos Dados",
      art_dice_style_stone: "Pedra",
      art_dice_style_coal: "Carvão",
      art_dice_style_wood: "Madeira",
      art_fonts: "Fontes",
      art_sounds: "Sons e Ambiente",
      art_anim: "Animações e Efeitos",
      art_design: "Meu Design",
      art_dev: "Em Desenvolvimento",
      art_bg_bright: "Brilho do Fundo",
      art_bg_trans: "Transparência do Fundo",
      art_bg_title: "Fundo",
      art_card_design: "Design das Cartas",
      art_choose_card: "Escolher Carta",
      art_particle_color: "Partícula",
      art_test_roll: "Rolagem de Teste",
      map_warning_title: "Mapa necessário!",
      map_warning_desc:
        "Apenas participantes no mapa atual podem ser adicionados.",
      mode_immersive: "Tabuleiro Immersivo",
      mode_classic: "Tabuleiro Clássico",
      limit_title: "Muitos participantes!",
      limit_desc:
        "Muitos participantes (Máx 10). Deseja reduzir ou usar o Modo Clássico?",
      limit_red: "Reduzir",
      limit_class: "Usar Modo Clássico",
      settings_perf: "Desempenho",
      settings_vol: "Volume",
      exit: "SAÍDA DE EMERGÊNCIA",
      acr: "Acrobacia",
      ani: "Lidar com Animais",
      arc: "Arcanismo",
      ath: "Atletismo",
      dec: "Enganação",
      his: "História",
      ins: "Intuição",
      itm: "Intimidação",
      inv: "Investigação",
      med: "Medicina",
      nat: "Natureza",
      prc: "Percepção",
      prf: "Atuação",
      per: "Persuasão",
      rel: "Religião",
      slt: "Prestidigitação",
      ste: "Furtividade",
      sur: "Sobrevivência",
      str: "Força",
      dex: "Destreza",
      con: "Constituição",
      int: "Inteligência",
      wis: "Sabedoria",
      cha: "Carisma",
      abl_str: "Força",
      abl_dex: "Destreza",
      abl_con: "Constituição",
      abl_int: "Inteligência",
      abl_wis: "Sabedoria",
      abl_cha: "Carisma",
      acrobatics: "Acrobacia",
      arcana: "Arcanismo",
      athletics: "Atletismo",
      crafting: "Manufatura",
      deception: "Enganação",
      diplomacy: "Diplomacia",
      intimidation: "Intimidação",
      medicine: "Medicina",
      nature: "Natureza",
      occultism: "Ocultismo",
      perception: "Percepção",
      performance: "Atuação",
      religion: "Religião",
      society: "Sociedade",
      stealth: "Furtividade",
      survival: "Sobrevivência",
      thievery: "Ladroagem",
      fortitude: "Fortitude",
      reflex: "Reflexos",
      will: "Vontade",
    },
    it: {
      btn_skills: "Prove di Abilità",
      btn_init: "Preparazione Combattimento",
      start_combat: "Inizia Combattimento",
      btn_random: "Carte del Destino",
      btn_start_roulette: "Scegli la tua carta",
      who_title: "CHI PARTECIPA?",
      drop_actor: "TRASCINA ATTORE O SELEZIONA",
      proceed: "VAI ALLA CONFIGURAZIONE",
      btn_wheel: "CARTE DEL DESTINO!",
      roll_it: "TIRA!",
      setup_title: "CONFIGURAZIONE",
      tab_skills: "ABILITÀ",
      tab_saves: "TIRI SALVEZZA",
      tab_abilities: "CARATTERISTICHE",
      tab_flat: "TIRI PURI",
      sel_global: "-- Seleziona Globale --",
      adj_diff: "Regola Difficoltà",
      pass_fail: "Successo / Fallimento",
      hidden_gm: "Nascosto",
      finish: "TERMINA E RISOLVI",
      spin: "MESCOLA",
      close: "CHIUDI",
      init_rolls: "Tiri di Iniziativa",
      mixed_rolls: "Tiri Misti",
      waiting: "In attesa...",
      result_crit_fail: "Fallimento Critico",
      result_fail: "Fallimento",
      result_succ: "Successo",
      result_crit_succ: "Successo Critico",
      init_text: "INIZIATIVA",
      level_dc: "CD PER LIVELLO",
      dc_adj: "REGOLAZIONE CD",
      flat_straight: "D20 Puro",
      flat_death: "Tiro Salvezza Morte",
      flat_persistent: "Danno Persistente",
      flat_concealed: "Occultato",
      flat_hidden: "Nascosto",
      flat_recovery: "Tiro di Recupero",
      resol_title: "🎬 Risultati Rollmate",
      secret_title: "🕵️ Tiri Segreti: Rollmate",
      started_title: "🎬 Rollmate Avviato",
      click_wheel: "Clicca per vedere le carte!",
      click_dice: "Clicca sul ritratto per tirare!",
      open_win: "APRI FINESTRA",
      gather_party: "Raduna il Gruppo!",
      gather_all: "Raduna Tutti",
      prep_combat: "Raduna combattenti",
      art_colors: "Colori",
      art_hover: "Colore Hover",
      art_border: "Bordo Finestra",
      art_dice_head: "Design Dadi",
      art_dice_style_stone: "Pietra",
      art_dice_style_coal: "Carbone",
      art_dice_style_wood: "Legno",
      art_fonts: "Font",
      art_sounds: "Suoni e Ambiente",
      art_anim: "Animazioni ed Effetti",
      art_design: "Il Mio Design",
      art_dev: "In Sviluppo",
      art_bg_bright: "Luminosità Sfondo",
      art_bg_trans: "Trasparenza Sfondo",
      art_bg_title: "Sfondo",
      art_card_design: "Design Carte",
      art_choose_card: "Scegli Carta",
      art_particle_color: "Particella",
      art_test_roll: "Tiro di Prova",
      map_warning_title: "Mappa richiesta!",
      map_warning_desc:
        "Possono essere aggiunti solo i partecipanti sulla mappa attuale.",
      mode_immersive: "Tabellone Immersivo",
      mode_classic: "Tabellone Classico",
      limit_title: "Troppi partecipanti!",
      limit_desc:
        "Troppi partecipanti (Max 10). Vuoi ridurre i partecipanti o usare il Modo Classico?",
      limit_red: "Riduci",
      limit_class: "Usa Modo Classico",
      settings_perf: "Prestazioni",
      settings_vol: "Volume",
      exit: "USCITA DI EMERGENZA",
      acr: "Acrobazia",
      ani: "Addestrare Animali",
      arc: "Arcano",
      ath: "Atletica",
      dec: "Inganno",
      his: "Storia",
      ins: "Intuizione",
      itm: "Intimidire",
      inv: "Indagare",
      med: "Medicina",
      nat: "Natura",
      prc: "Percezione",
      prf: "Intrattenere",
      per: "Persuasione",
      rel: "Religione",
      slt: "Rapidità di Mano",
      ste: "Furtività",
      sur: "Sopravvivenza",
      str: "Forza",
      dex: "Destrezza",
      con: "Costituzione",
      int: "Intelligenza",
      wis: "Saggezza",
      cha: "Carisma",
      abl_str: "Forza",
      abl_dex: "Destrezza",
      abl_con: "Costituzione",
      abl_int: "Intelligenza",
      abl_wis: "Saggezza",
      abl_cha: "Carisma",
      acrobatics: "Acrobazia",
      arcana: "Arcano",
      athletics: "Atletica",
      crafting: "Artigianato",
      deception: "Inganno",
      diplomacy: "Diplomazia",
      intimidation: "Intimidazione",
      medicine: "Medicina",
      nature: "Natura",
      occultism: "Occultismo",
      perception: "Percezione",
      performance: "Esibizione",
      religion: "Religione",
      society: "Società",
      stealth: "Furtività",
      survival: "Sopravvivenza",
      thievery: "Furto",
      fortitude: "Tempra",
      reflex: "Riflessi",
      will: "Volontà",
    },
    pl: {
      btn_skills: "Testy Umiejętności",
      btn_init: "Przygotowanie do Walki",
      start_combat: "Rozpocznij Walkę",
      btn_random: "Karty Przeznaczenia",
      btn_start_roulette: "Wybierz swoją kartę",
      who_title: "KTO BIERZE UDZIAŁ?",
      drop_actor: "PRZECIĄGNIJ AKTORA LUB WYBIERZ",
      proceed: "PRZEJDŹ DO USTAWIEŃ",
      btn_wheel: "KARTY PRZEZNACZENIA!",
      roll_it: "RZUCAJ!",
      setup_title: "USTAWIENIA",
      tab_skills: "UMIEJĘTNOŚCI",
      tab_saves: "RZUTY OBRONNE",
      tab_abilities: "CECHY",
      tab_flat: "ZWYKŁE RZUTY",
      sel_global: "-- Wybierz Globalnie --",
      adj_diff: "Dostosuj Trudność",
      pass_fail: "Sukces / Porażka",
      hidden_gm: "Ukryty",
      finish: "ZAKOŃCZ I ROZWIĄŻ",
      spin: "TASUJ",
      close: "ZAMKNIJ",
      init_rolls: "Rzuty na Inicjatywę",
      mixed_rolls: "Mieszane Rzuty",
      waiting: "Oczekiwanie...",
      result_crit_fail: "Kryt. Porażka",
      result_fail: "Porażka",
      result_succ: "Sukces",
      result_crit_succ: "Kryt. Sukces",
      init_text: "INICJATYWA",
      level_dc: "ST PODEJŚCIA",
      dc_adj: "MODYFIKATOR ST",
      flat_straight: "Zwykłe D20",
      flat_death: "Rzut Obronny na Śmierć",
      flat_persistent: "Obrażenia Ciągłe",
      flat_concealed: "Ukryty",
      flat_hidden: "Schowany",
      flat_recovery: "Test Powrotu",
      resol_title: "🎬 Wyniki Rollmate",
      secret_title: "🕵️ Tajne Rzuty: Rollmate",
      started_title: "🎬 Rollmate Uruchomiony",
      click_wheel: "Kliknij, aby zobaczyć karty!",
      click_dice: "Kliknij portret, aby rzucić!",
      open_win: "OTWÓRZ OKNO",
      gather_party: "Zbierz Drużynę!",
      gather_all: "Zbierz Wszystkich",
      prep_combat: "Zbierz walczących",
      art_colors: "Kolory",
      art_hover: "Kolor Najechania",
      art_border: "Ramka Okna",
      art_dice_head: "Wygląd Kości",
      art_dice_style_stone: "Kamień",
      art_dice_style_coal: "Węgiel",
      art_dice_style_wood: "Drewno",
      art_fonts: "Czcionki",
      art_sounds: "Dźwięki i Atmosfera",
      art_anim: "Animacje i Efekty",
      art_design: "Mój Wygląd",
      art_dev: "W Trakcie Rozwoju",
      art_bg_bright: "Jasność Tła",
      art_bg_trans: "Przezroczystość Tła",
      art_bg_title: "Tło",
      art_card_design: "Wygląd Kart",
      art_choose_card: "Wybierz Kartę",
      art_particle_color: "Cząsteczki",
      art_test_roll: "Rzut Testowy",
      map_warning_title: "Wymagana mapa!",
      map_warning_desc: "Można dodać tylko uczestników z obecnej mapy.",
      mode_immersive: "Tablica Immersyjna",
      mode_classic: "Tablica Klasyczna",
      limit_title: "Zbyt wielu uczestników!",
      limit_desc:
        "Zbyt wielu uczestników (Maks 10). Czy chcesz zredukować ich liczbę czy użyć Trybu Klasycznego?",
      limit_red: "Redukuj",
      limit_class: "Użyj Trybu Klasycznego",
      settings_perf: "Wydajność",
      settings_vol: "Głośność",
      exit: "WYJŚCIE AWARYJNE",
      acr: "Akrobatyka",
      ani: "Opieka nad Zwierzętami",
      arc: "Wiedza Tajemna",
      ath: "Atletyka",
      dec: "Oszustwo",
      his: "Historia",
      ins: "Przenikliwość",
      itm: "Zastraszanie",
      inv: "Śledztwo",
      med: "Medycyna",
      nat: "Natura",
      prc: "Percepcja",
      prf: "Występy",
      per: "Perswazja",
      rel: "Religia",
      slt: "Zwinne Dłonie",
      ste: "Skradanie",
      sur: "Sztuka Przetrwania",
      str: "Siła",
      dex: "Zręczność",
      con: "Kondycja",
      int: "Inteligencja",
      wis: "Mądrość",
      cha: "Charyzma",
      abl_str: "Siła",
      abl_dex: "Zręczność",
      abl_con: "Kondycja",
      abl_int: "Inteligencja",
      abl_wis: "Mądrość",
      abl_cha: "Charyzma",
      acrobatics: "Akrobatyka",
      arcana: "Wiedza Tajemna",
      athletics: "Atletyka",
      crafting: "Rzemiosło",
      deception: "Oszustwo",
      diplomacy: "Dyplomacja",
      intimidation: "Zastraszanie",
      medicine: "Medycyna",
      nature: "Natura",
      occultism: "Okultyzm",
      perception: "Percepcja",
      performance: "Występy",
      religion: "Religia",
      society: "Społeczeństwo",
      stealth: "Skradanie",
      survival: "Sztuka Przetrwania",
      thievery: "Złodziejstwo",
      fortitude: "Wytwałość",
      reflex: "Refleks",
      will: "Wola",
    },
    nl: {
      btn_skills: "Vaardigheidscontroles",
      btn_init: "Gevechtsvoorbereiding",
      start_combat: "Start Gevecht",
      btn_random: "Kaarten van het Lot",
      btn_start_roulette: "Kies je kaart",
      who_title: "WIE DOEN ER MEE?",
      drop_actor: "SLEEP ACTEUR OF SELECTEER",
      proceed: "GA NAAR INSTELLINGEN",
      btn_wheel: "KAARTEN VAN HET LOT!",
      roll_it: "GOOI!",
      setup_title: "INSTELLINGEN",
      tab_skills: "VAARDIGHEDEN",
      tab_saves: "REDDINGS WORPEN",
      tab_abilities: "EIGENSCHAPPEN",
      tab_flat: "STANDAARD GOOI",
      sel_global: "-- Selecteer Globaal --",
      adj_diff: "Pas Moeilijkheid Aan",
      pass_fail: "Succes / Falen",
      hidden_gm: "Verborgen",
      finish: "VOLTOOI EN LOS OP",
      spin: "SCHUDDEN",
      close: "SLUITEN",
      init_rolls: "Initiatief Worpen",
      mixed_rolls: "Gemengde Worpen",
      waiting: "Wachten...",
      result_crit_fail: "Kritiek Falen",
      result_fail: "Falen",
      result_succ: "Succes",
      result_crit_succ: "Kritiek Succes",
      init_text: "INITIATIEF",
      level_dc: "NIVEAU DC",
      dc_adj: "DC AANPASSING",
      flat_straight: "Standaard D20",
      flat_death: "Dood Reddingsworp",
      flat_persistent: "Aanhoudende Schade",
      flat_concealed: "Verborgen",
      flat_hidden: "Verstopt",
      flat_recovery: "Herstel Worp",
      resol_title: "🎬 Rollmate Resultaten",
      secret_title: "🕵️ Geheime Worpen: Rollmate",
      started_title: "🎬 Rollmate Gestart",
      click_wheel: "Klik om de kaarten te zien!",
      click_dice: "Klik op het portret om te gooien!",
      open_win: "OPEN VENSTER",
      gather_party: "Verzamel Groep!",
      gather_all: "Verzamel Iedereen",
      prep_combat: "Verzamel strijders",
      art_colors: "Kleuren",
      art_hover: "Hover Kleur",
      art_border: "Venster Rand",
      art_dice_head: "Dobbelsteen Ontwerp",
      art_dice_style_stone: "Steen",
      art_dice_style_coal: "Kool",
      art_dice_style_wood: "Hout",
      art_fonts: "Lettertypen",
      art_sounds: "Geluiden en Sfeer",
      art_anim: "Animaties en Effecten",
      art_design: "Mijn Ontwerp",
      art_dev: "In Ontwikkeling",
      art_bg_bright: "Achtergrond Helderheid",
      art_bg_trans: "Achtergrond Transparantie",
      art_bg_title: "Achtergrond",
      art_card_design: "Kaart Ontwerp",
      art_choose_card: "Kies Kaart",
      art_particle_color: "Deeltjes",
      art_test_roll: "Test Worp",
      map_warning_title: "Map vereist!",
      map_warning_desc:
        "Alleen deelnemers op de huidige map kunnen worden toegevoegd.",
      mode_immersive: "Immersief Bord",
      mode_classic: "Klassiek Bord",
      limit_title: "Te veel deelnemers!",
      limit_desc:
        "Te veel deelnemers (Max 10). Wil je verminderen of overschakelen naar de Klassieke Modus?",
      limit_red: "Verminderen",
      limit_class: "Gebruik Klassieke Modus",
      settings_perf: "Prestaties",
      settings_vol: "Volume",
      exit: "NOODUITGANG",
      acr: "Acrobatiek",
      ani: "Met Dieren Omgaan",
      arc: "Arcana",
      ath: "Atletiek",
      dec: "Misleiding",
      his: "Geschiedenis",
      ins: "Inzicht",
      itm: "Intimidatie",
      inv: "Onderzoek",
      med: "Geneeskunde",
      nat: "Natuur",
      prc: "Waarneming",
      prf: "Optreden",
      per: "Overtuiging",
      rel: "Religie",
      slt: "Vingervlugheid",
      ste: "Heimelijkheid",
      sur: "Overleven",
      str: "Kracht",
      dex: "Behendigheid",
      con: "Constitutie",
      int: "Intelligentie",
      wis: "Wijsheid",
      cha: "Charisma",
      abl_str: "Kracht",
      abl_dex: "Behendigheid",
      abl_con: "Constitutie",
      abl_int: "Intelligentie",
      abl_wis: "Wijsheid",
      abl_cha: "Charisma",
      acrobatics: "Acrobatiek",
      arcana: "Arcana",
      athletics: "Atletiek",
      crafting: "Ambacht",
      deception: "Misleiding",
      diplomacy: "Diplomatie",
      intimidation: "Intimidatie",
      medicine: "Geneeskunde",
      nature: "Natuur",
      occultism: "Occultisme",
      perception: "Waarneming",
      performance: "Optreden",
      religion: "Religie",
      society: "Maatschappij",
      stealth: "Heimelijkheid",
      survival: "Overleven",
      thievery: "Diefstal",
      fortitude: "Taaiheid",
      reflex: "Reflex",
      will: "Wil",
    },
    ru: {
      btn_skills: "Проверки навыков",
      btn_init: "Подготовка к бою",
      start_combat: "Начать бой",
      btn_random: "Карты Судьбы",
      btn_start_roulette: "Выберите карту",
      who_title: "КТО УЧАСТВУЕТ?",
      drop_actor: "ПЕРЕТАЩИТЕ ИЛИ ВЫБЕРИТЕ",
      proceed: "ПЕРЕЙТИ К НАСТРОЙКЕ",
      btn_wheel: "КАРТЫ СУДЬБЫ!",
      roll_it: "БРОСОК!",
      setup_title: "НАСТРОЙКА",
      tab_skills: "НАВЫКИ",
      tab_saves: "СПАСБРОСКИ",
      tab_abilities: "ХАРАКТЕРИСТИКИ",
      tab_flat: "ОБЫЧНЫЕ БРОСКИ",
      sel_global: "-- Выбрать глобально --",
      adj_diff: "Настроить сложность",
      pass_fail: "Успех / Провал",
      hidden_gm: "Скрыто",
      finish: "ЗАВЕРШИТЬ И РАЗРЕШИТЬ",
      spin: "ТАВАСОВАТЬ",
      close: "ЗАКРЫТЬ",
      init_rolls: "Броски инициативы",
      mixed_rolls: "Смешанные броски",
      waiting: "Ожидание...",
      result_crit_fail: "Крит. Провал",
      result_fail: "Провал",
      result_succ: "Успех",
      result_crit_succ: "Крит. Успех",
      init_text: "ИНИЦИАТИВА",
      level_dc: "СЛОЖНОСТЬ ПО УРОВНЮ",
      dc_adj: "ПОПРАВКА СЛОЖНОСТИ",
      flat_straight: "Обычный D20",
      flat_death: "Спасбросок от смерти",
      flat_persistent: "Постоянный урон",
      flat_concealed: "Скрыт",
      flat_hidden: "Спрятан",
      flat_recovery: "Бросок восстановления",
      resol_title: "🎬 Результаты Rollmate",
      secret_title: "🕵️ Тайные броски: Rollmate",
      started_title: "🎬 Rollmate запущен",
      click_wheel: "Нажмите, чтобы увидеть карты!",
      click_dice: "Нажмите на портрет для броска!",
      open_win: "ОТКРЫТЬ ОКНО",
      gather_party: "Собрать группу!",
      gather_all: "Собрать всех",
      prep_combat: "Собрать бойцов",
      art_colors: "Цвета",
      art_hover: "Цвет при наведении",
      art_border: "Рамка окна",
      art_dice_head: "Дизайн кубиков",
      art_dice_style_stone: "Камень",
      art_dice_style_coal: "Уголь",
      art_dice_style_wood: "Дерево",
      art_fonts: "Шрифты",
      art_sounds: "Звуки и атмосфера",
      art_anim: "Анимации и эффекты",
      art_design: "Мой дизайн",
      art_dev: "В разработке",
      art_bg_bright: "Яркость фона",
      art_bg_trans: "Прозрачность фона",
      art_bg_title: "Фон",
      art_card_design: "Дизайн карт",
      art_choose_card: "Выбрать карту",
      art_particle_color: "Частицы",
      art_test_roll: "Тестовый бросок",
      map_warning_title: "Требуется карта!",
      map_warning_desc: "Можно добавлять только участников с текущей карты.",
      mode_immersive: "Иммерсивная доска",
      mode_classic: "Классическая доска",
      limit_title: "Слишком много участников!",
      limit_desc:
        "Слишком много участников (Макс 10). Хотите сократить их количество или использовать Классический режим?",
      limit_red: "Сократить",
      limit_class: "Использовать Классический режим",
      settings_perf: "Производительность",
      settings_vol: "Громкость",
      exit: "АВАРИЙНЫЙ ВЫХОД",
      acr: "Акробатика",
      ani: "Уход за животными",
      arc: "Магия",
      ath: "Атлетика",
      dec: "Обман",
      his: "История",
      ins: "Проницательность",
      itm: "Запугивание",
      inv: "Анализ",
      med: "Медицина",
      nat: "Природа",
      prc: "Внимательность",
      prf: "Выступление",
      per: "Убеждение",
      rel: "Религия",
      slt: "Ловкость рук",
      ste: "Скрытность",
      sur: "Выживание",
      str: "Сила",
      dex: "Ловкость",
      con: "Телосложение",
      int: "Интеллект",
      wis: "Мудрость",
      cha: "Харизма",
      abl_str: "Сила",
      abl_dex: "Ловкость",
      abl_con: "Телосложение",
      abl_int: "Интеллект",
      abl_wis: "Мудрость",
      abl_cha: "Харизма",
      acrobatics: "Акробатика",
      arcana: "Магия",
      athletics: "Атлетика",
      crafting: "Ремесло",
      deception: "Обман",
      diplomacy: "Дипломатия",
      intimidation: "Запугивание",
      medicine: "Медицина",
      nature: "Природа",
      occultism: "Оккультизм",
      perception: "Внимательность",
      performance: "Выступление",
      religion: "Религия",
      society: "Общество",
      stealth: "Скрытность",
      survival: "Выживание",
      thievery: "Воровство",
      fortitude: "Стойкость",
      reflex: "Реакция",
      will: "Воля",
    },
    ja: {
      btn_skills: "スキルチェック",
      btn_init: "戦闘準備",
      start_combat: "戦闘開始",
      btn_random: "運命のカード",
      btn_start_roulette: "カードを選ぶ",
      who_title: "誰が参加しますか？",
      drop_actor: "アクターをドロップまたは選択",
      proceed: "設定に進む",
      btn_wheel: "運命のカード！",
      roll_it: "ロール！",
      setup_title: "設定",
      tab_skills: "スキル",
      tab_saves: "セービングスロー",
      tab_abilities: "能力値",
      tab_flat: "通常ロール",
      sel_global: "-- 全体を選択 --",
      adj_diff: "難易度調整",
      pass_fail: "成功 / 失敗",
      hidden_gm: "非公開",
      finish: "完了して解決",
      spin: "シャッフル",
      close: "閉じる",
      init_rolls: "イニシアチブ・ロール",
      mixed_rolls: "複合ロール",
      waiting: "待機中...",
      result_crit_fail: "クリティカル失敗",
      result_fail: "失敗",
      result_succ: "成功",
      result_crit_succ: "クリティカル成功",
      init_text: "イニシアチブ",
      level_dc: "レベル別難易度",
      dc_adj: "難易度補正",
      flat_straight: "通常D20",
      flat_death: "デスセーブ",
      flat_persistent: "継続ダメージ",
      flat_concealed: "秘匿",
      flat_hidden: "隠伏",
      flat_recovery: "回復チェック",
      resol_title: "🎬 Rollmate 結果",
      secret_title: "🕵️ シークレット・ロール",
      started_title: "🎬 Rollmate 開始",
      click_wheel: "クリックしてカードを見る！",
      click_dice: "ポートレートをクリックしてロール！",
      open_win: "ウィンドウを開く",
      gather_party: "パーティを集める！",
      gather_all: "全員を集める",
      prep_combat: "戦闘員を集める",
      art_colors: "色",
      art_hover: "ホバーカラー",
      art_border: "ウィンドウ枠",
      art_dice_head: "ダイスデザイン",
      art_dice_style_stone: "石",
      art_dice_style_coal: "石炭",
      art_dice_style_wood: "木",
      art_fonts: "フォント",
      art_sounds: "サウンドと環境音",
      art_anim: "アニメーションとエフェクト",
      art_design: "マイデザイン",
      art_dev: "開発中",
      art_bg_bright: "背景の明るさ",
      art_bg_trans: "背景の透明度",
      art_bg_title: "背景",
      art_card_design: "カードデザイン",
      art_choose_card: "カードを選ぶ",
      art_particle_color: "パーティクル",
      art_test_roll: "テストロール",
      map_warning_title: "マップが必要です！",
      map_warning_desc: "現在のマップにいる参加者のみ追加できます。",
      mode_immersive: "没入型ボード",
      mode_classic: "クラシックボード",
      limit_title: "参加者が多すぎます！",
      limit_desc:
        "没入型ボードの参加者が多すぎます（最大10人）。参加者を減らすか、クラシックモードに切り替えますか？",
      limit_red: "減らす",
      limit_class: "クラシックモードを使用",
      settings_perf: "パフォーマンス",
      settings_vol: "音量",
      exit: "緊急脱出",
      acr: "軽業",
      ani: "動物使い",
      arc: "魔法学",
      ath: "運動",
      dec: "ペテン",
      his: "歴史",
      ins: "看破",
      itm: "威圧",
      inv: "捜査",
      med: "医術",
      nat: "自然",
      prc: "知覚",
      prf: "芸能",
      per: "説得",
      rel: "宗教",
      slt: "手先の早業",
      ste: "隠密",
      sur: "生存",
      str: "筋力",
      dex: "敏捷力",
      con: "耐久力",
      int: "知力",
      wis: "判断力",
      cha: "魅力",
      abl_str: "筋力",
      abl_dex: "敏捷力",
      abl_con: "耐久力",
      abl_int: "知力",
      abl_wis: "判断力",
      abl_cha: "魅力",
      acrobatics: "軽業",
      arcana: "魔法学",
      athletics: "運動",
      crafting: "製作",
      deception: "ペテン",
      diplomacy: "交渉",
      intimidation: "威圧",
      medicine: "医術",
      nature: "自然",
      occultism: "オカルト",
      perception: "知覚",
      performance: "芸能",
      religion: "宗教",
      society: "社会",
      stealth: "隠密",
      survival: "生存",
      thievery: "盗賊",
      fortitude: "頑健",
      reflex: "反応",
      will: "意志",
    },
    ko: {
      btn_skills: "스킬 판정",
      btn_init: "전투 준비",
      start_combat: "전투 시작",
      btn_random: "운명의 카드",
      btn_start_roulette: "카드 선택",
      who_title: "누가 참여합니까?",
      drop_actor: "액터 드래그 또는 선택",
      proceed: "설정으로 이동",
      btn_wheel: "운명의 카드!",
      roll_it: "주사위 굴리기!",
      setup_title: "설정",
      tab_skills: "스킬",
      tab_saves: "내성 굴림",
      tab_abilities: "능력치",
      tab_flat: "일반 굴림",
      sel_global: "-- 전체 선택 --",
      adj_diff: "난이도 조정",
      pass_fail: "성공 / 실패",
      hidden_gm: "비공개",
      finish: "완료 및 해결",
      spin: "섞기",
      close: "닫기",
      init_rolls: "우선권 굴림",
      mixed_rolls: "혼합 굴림",
      waiting: "대기 중...",
      result_crit_fail: "치명적 실패",
      result_fail: "실패",
      result_succ: "성공",
      result_crit_succ: "치명적 성공",
      init_text: "우선권",
      level_dc: "레벨별 난이도",
      dc_adj: "난이도 보정",
      flat_straight: "일반 D20",
      flat_death: "죽음 내성",
      flat_persistent: "지속 피해",
      flat_concealed: "은폐",
      flat_hidden: "숨음",
      flat_recovery: "회복 판정",
      resol_title: "🎬 Rollmate 결과",
      secret_title: "🕵️ 비밀 굴림",
      started_title: "🎬 Rollmate 시작됨",
      click_wheel: "클릭하여 카드를 확인하세요!",
      click_dice: "초상화를 클릭하여 굴리세요!",
      open_win: "창 열기",
      gather_party: "파티 모으기!",
      gather_all: "모 모두 모으기",
      prep_combat: "전투원 모으기",
      art_colors: "색상",
      art_hover: "호버 색상",
      art_border: "창 테두리",
      art_dice_head: "주사위 디자인",
      art_dice_style_stone: "돌",
      art_dice_style_coal: "석탄",
      art_dice_style_wood: "나무",
      art_fonts: "글꼴",
      art_sounds: "사운드 및 환경음",
      art_anim: "애니메이션 및 효과",
      art_design: "내 디자인",
      art_dev: "개발 중",
      art_bg_bright: "배경 밝기",
      art_bg_trans: "배경 투명도",
      art_bg_title: "배경",
      art_card_design: "카드 디자인",
      art_choose_card: "카드 선택",
      art_particle_color: "파티클",
      art_test_roll: "테스트 굴림",
      map_warning_title: "맵이 필요합니다!",
      map_warning_desc: "현재 맵에 있는 참가자만 추가할 수 있습니다.",
      mode_immersive: "몰입형 보드",
      mode_classic: "클래식 보드",
      limit_title: "참가자가 너무 많습니다!",
      limit_desc:
        "참가자가 너무 많습니다 (최대 10명). 참가자를 줄이거나 클래식 모드로 전환하시겠습니까?",
      limit_red: "줄이기",
      limit_class: "클래식 모드 사용",
      settings_perf: "성능",
      settings_vol: "볼륨",
      exit: "비상 탈출",
      acr: "곡예",
      ani: "동물 조련",
      arc: "비전",
      ath: "운동",
      dec: "기만",
      his: "역사",
      ins: "통찰",
      itm: "위협",
      inv: "조사",
      med: "의학",
      nat: "자연",
      prc: "지각",
      prf: "공연",
      per: "설득",
      rel: "종교",
      slt: "손재주",
      ste: "은신",
      sur: "생존",
      str: "근력",
      dex: "민첩",
      con: "건강",
      int: "지능",
      wis: "지혜",
      cha: "매력",
      abl_str: "근력",
      abl_dex: "민첩",
      abl_con: "건강",
      abl_int: "지능",
      abl_wis: "지혜",
      abl_cha: "매력",
      acrobatics: "곡예",
      arcana: "비전",
      athletics: "운동",
      crafting: "제작",
      deception: "기만",
      diplomacy: "외교",
      intimidation: "위협",
      medicine: "의학",
      nature: "자연",
      occultism: "오컬트",
      perception: "지각",
      performance: "공연",
      religion: "종교",
      society: "사회",
      stealth: "은신",
      survival: "생존",
      thievery: "도둑질",
      fortitude: "인내",
      reflex: "반사",
      will: "의지",
    },
    zh: {
      btn_skills: "技能检定",
      btn_init: "战斗准备",
      start_combat: "开始战斗",
      btn_random: "命运之牌",
      btn_start_roulette: "选择你的卡牌",
      who_title: "谁参与其中？",
      drop_actor: "拖放角色或选择",
      proceed: "前往设置",
      btn_wheel: "命运之牌！",
      roll_it: "投掷！",
      setup_title: "设置",
      tab_skills: "技能",
      tab_saves: "豁免",
      tab_abilities: "能力",
      tab_flat: "普通投掷",
      sel_global: "-- 全局选择 --",
      adj_diff: "调整难度",
      pass_fail: "成功 / 失败",
      hidden_gm: "暗投",
      finish: "完成并结算",
      spin: "洗牌",
      close: "关闭",
      init_rolls: "先攻投掷",
      mixed_rolls: "混合投掷",
      waiting: "等待中...",
      result_crit_fail: "大失败",
      result_fail: "失败",
      result_succ: "成功",
      result_crit_succ: "大成功",
      init_text: "先攻",
      level_dc: "等级难度",
      dc_adj: "难度调整",
      flat_straight: "普通D20",
      flat_death: "死亡豁免",
      flat_persistent: "持续伤害",
      flat_concealed: "隐蔽",
      flat_hidden: "隐藏",
      flat_recovery: "恢复检定",
      resol_title: "🎬 Rollmate 结果",
      secret_title: "🕵️ 暗投记录",
      started_title: "🎬 Rollmate 已启动",
      click_wheel: "点击查看卡牌！",
      click_dice: "点击头像投掷！",
      open_win: "打开窗口",
      gather_party: "召集队伍！",
      gather_all: "召集所有人",
      prep_combat: "召集战斗员",
      art_colors: "颜色",
      art_hover: "悬停颜色",
      art_border: "窗口边框",
      art_dice_head: "骰子设计",
      art_dice_style_stone: "石头",
      art_dice_style_coal: "煤炭",
      art_dice_style_wood: "木头",
      art_fonts: "字体",
      art_sounds: "声音与环境",
      art_anim: "动画与效果",
      art_design: "我的设计",
      art_dev: "开发中",
      art_bg_bright: "背景亮度",
      art_bg_trans: "背景透明度",
      art_bg_title: "背景",
      art_card_design: "卡牌设计",
      art_choose_card: "选择卡牌",
      art_particle_color: "粒子",
      art_test_roll: "测试投掷",
      map_warning_title: "需要地图！",
      map_warning_desc: "只能添加当前地图上的参与者。",
      mode_immersive: "沉浸式面板",
      mode_classic: "经典面板",
      limit_title: "参与者过多！",
      limit_desc: "参与者过多 (最多 10 人)。是否减少参与者或使用经典模式？",
      limit_red: "减少",
      limit_class: "使用经典模式",
      settings_perf: "性能",
      settings_vol: "音量",
      exit: "紧急退出",
      acr: "杂技",
      ani: "驯兽",
      arc: "奥秘",
      ath: "运动",
      dec: "欺瞒",
      his: "历史",
      ins: "洞悉",
      itm: "威吓",
      inv: "调查",
      med: "医药",
      nat: "自然",
      prc: "察觉",
      prf: "表演",
      per: "游说",
      rel: "宗教",
      slt: "巧手",
      ste: "隐匿",
      sur: "生存",
      str: "力量",
      dex: "敏捷",
      con: "体质",
      int: "智力",
      wis: "感知",
      cha: "魅力",
      abl_str: "力量",
      abl_dex: "敏捷",
      abl_con: "体质",
      abl_int: "智力",
      abl_wis: "感知",
      abl_cha: "魅力",
      acrobatics: "杂技",
      arcana: "奥秘",
      athletics: "运动",
      crafting: "手艺",
      deception: "欺瞒",
      diplomacy: "交涉",
      intimidation: "威吓",
      medicine: "医药",
      nature: "自然",
      occultism: "神秘",
      perception: "察觉",
      performance: "表演",
      religion: "宗教",
      society: "社会",
      stealth: "隐匿",
      survival: "生存",
      thievery: "贼活",
      fortitude: "强韧",
      reflex: "反射",
      will: "意志",
    },
  };

  let currentLang = game.user.getFlag(flagScope, "rollmateLanguage") ?? "en";
  if (!langDict[currentLang]) currentLang = "en";
  const t = (key) =>
    (langDict[currentLang] && langDict[currentLang][key]) ||
    langDict["en"][key] ||
    key;

  const langLabels = {
    en: "English",
    de: "Deutsch",
    es: "Español",
    fr: "Français",
    pt: "Português",
    it: "Italiano",
    pl: "Polski",
    nl: "Nederlands",
    ru: "Русский",
    ja: "日本語",
    ko: "한국어",
    zh: "中文",
  };
  const langFlags = {
    en: "gb",
    de: "de",
    es: "es",
    fr: "fr",
    pt: "pt",
    it: "it",
    pl: "pl",
    nl: "nl",
    ru: "ru",
    ja: "jp",
    ko: "kr",
    zh: "cn",
  };

  window.changeRollmateLanguage = async function (lang) {
    await game.user.setFlag(flagScope, "rollmateLanguage", lang);
    currentLang = lang;

    const view = $(`#${overlayId}`);
    if (view.find(".start-menu-container").length > 0) {
      showStartMenu();
    } else if (view.find("#setup-step-4").length > 0) {
      const isStep4 = !view.find("#setup-step-4").hasClass("hidden");
      const mode = view.find("#btn-actors-next").data("mode");

      const selectedActors = [];
      view.find("#actor-selection-stage .selected").each(function () {
        selectedActors.push($(this).data("id"));
      });

      startSetup(mode, isStep4 ? 4 : 3, selectedActors);
    }
  };

  function toggleMacroIcon(show) {
    if (show) {
      $(".rollmate-main-btn").show();
    } else {
      $(".rollmate-main-btn").hide();
    }
  }

  return {
    langDict,
    langFlags,
    langLabels,
    get currentLang() {
      return currentLang;
    },
    t,
    changeLang,
  };
})();
